apiVersion: apps/v1
kind: Deployment
metadata:
  name: statping
  labels:
    app: statping
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  revisionHistoryLimit: 10
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 50%
  template:
    metadata:
      labels:
        app: statping
        octopusexport: OctopusExport
    spec:
      containers:
        - name: cntnr
          image: statping/statping
          imagePullPolicy: IfNotPresent
          ports:
            - name: dflt
              containerPort: 8080
              protocol: TCP
