apiVersion: v1
kind: Service
metadata:
  annotations:
    generated: by 8gwifi.org
  name: statping
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: statping
  type: ClusterIP

